name: 'bundeshost'
version: '0.1.0'
config-version: 2

profile: 'bundeshost'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bundeshost:
    staging:
      +materialized: view
      +schema: stg
    marts:
      +materialized: table
      +schema: mart